### ISSUE TITLE
Setting state variable back to default on instance causes game to restart

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1159]
![15_22 49 27](https://github.com/vchelaru/FlatRedBall/assets/729631/c2f6a52c-a09f-44b8-8e8c-f4ebbaea5710)

```
10:38:17 PM - System.InvalidOperationException: Attempting to set property Red of type System.Single to value 1 with type System.String
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 94
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 492
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 408
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 205
GlueVariableSetData:
{
  "AssignOrRecordOnly": 0,
  "InstanceOwnerGameType": "LiveEditTest.Screens.Level1",
  "VariableName": "this.Enemy2.SpriteInstance.Red",
  "VariableValue": "1",
  "Type": null,
  "IsState": false,
  "ScreenSave": null,
  "EntitySave": null,
  "NamedObjectsToUpdate": []
}
10:38:17 PM - System.InvalidOperationException: Attempting to set property Red of type System.Single to value 1 with type System.String
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 94
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 492
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 357
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 408
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 205
GlueVariableSetData:
{
  "AssignOrRecordOnly": 0,
  "InstanceOwnerGameType": "LiveEditTest.Screens.Level1",
  "VariableName": "this.Enemy2.SpriteInstance.Red",
  "VariableValue": "1",
  "Type": null,
  "IsState": false,
  "ScreenSave": null,
  "EntitySave": null,
  "NamedObjectsToUpdate": []
}
10:46:55 PM - System.InvalidOperationException: Attempting to set property Red of type System.Single to value 1 with type System.String
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 94
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 492
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 408
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 205
GlueVariableSetData:
{
  "AssignOrRecordOnly": 0,
  "InstanceOwnerGameType": "LiveEditTest.Screens.Level1",
  "VariableName": "this.Enemy8.SpriteInstance.Red",
  "VariableValue": "1",
  "Type": null,
  "IsState": false,
  "ScreenSave": null,
  "EntitySave": null,
  "NamedObjectsToUpdate": []
}
10:46:55 PM - System.InvalidOperationException: Attempting to set property Red of type System.Single to value 1 with type System.String
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 94
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 492
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 357
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 408
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 205
GlueVariableSetData:
{
  "AssignOrRecordOnly": 0,
  "InstanceOwnerGameType": "LiveEditTest.Screens.Level1",
  "VariableName": "this.Enemy8.SpriteInstance.Red",
  "VariableValue": "1",
  "Type": null,
  "IsState": false,
  "ScreenSave": null,
  "EntitySave": null,
  "NamedObjectsToUpdate": []
}
10:49:25 PM - System.InvalidOperationException: Attempting to set property Red of type System.Single to value 1 with type System.String
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 94
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 492
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 408
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 205
GlueVariableSetData:
{
  "AssignOrRecordOnly": 0,
  "InstanceOwnerGameType": "LiveEditTest.Screens.Level1",
  "VariableName": "this.Enemy9.SpriteInstance.Red",
  "VariableValue": "1",
  "Type": null,
  "IsState": false,
  "ScreenSave": null,
  "EntitySave": null,
  "NamedObjectsToUpdate": []
}
10:49:25 PM - System.InvalidOperationException: Attempting to set property Red of type System.Single to value 1 with type System.String
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 94
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 492
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 357
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 408
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 205
GlueVariableSetData:
{
  "AssignOrRecordOnly": 0,
  "InstanceOwnerGameType": "LiveEditTest.Screens.Level1",
  "VariableName": "this.Enemy9.SpriteInstance.Red",
  "VariableValue": "1",
  "Type": null,
  "IsState": false,
  "ScreenSave": null,
  "EntitySave": null,
  "NamedObjectsToUpdate": []
}
```

**Comment by vchelaru** [comment]
Fixed.
