### ISSUE TITLE
Assigning bool? value in live edit causes game to restart due to failure to parse bool?

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1173]
```
1:19:07 PM - System.InvalidOperationException: Attempting to set property ForceFlipHorizontal of type System.Nullable`1[System.Boolean] to value True with type System.String
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 94
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 492
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\GitHub\Kimuzukash-chibi-kuto-urufu\CrankyChibiCthulu\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 408
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\GitHub\Kimuzukash-chibi-kuto-urufu\CrankyChibiCthulu\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 205
GlueVariableSetData:
{
  "AssignOrRecordOnly": 0,
  "InstanceOwnerGameType": "CrankyChibiCthulu.Screens.VicLevel1",
  "VariableName": "this.VineHand2.ForceFlipHorizontal",
  "VariableValue": "True",
  "Type": "Nullable<Boolean>",
  "IsState": false,
  "ScreenSave": null,
  "EntitySave": null,
  "NamedObjectsToUpdate": []
}
```

**Comment by vchelaru** [comment]
Fixed.
