### ISSUE TITLE
Fresh install of FRB from website results in game that crashes

### ISSUE THREAD

**Issue by Thraka** [vchelaru/FlatRedBall#1185]
I just downloaded FRB standalone from the website, ran the editor, created a new project of the topdown game, and pressed F5 to run. It crashed saying 

```
System.IO.FileLoadException: Could not load file or assembly 'FlatRedBallDesktopGLNet6, Version=2023.9.18.537, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'FlatRedBallDesktopGLNet6, Version=2023.9.18.537, Culture=neutral, PublicKeyToken=null'
   at MyProject.Game1.GeneratedInitialize()
   at MyProject.Game1.Initialize() in C:\Code\Fun\FlatRedBall\Projects\MyProject\MyProject\Game1.cs:line 66
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at MyProject.Program.Main(String[] args) in C:\Code\Fun\FlatRedBall\Projects\MyProject\MyProject\Program.cs:line 25
```

It looks like the NuGet package referenced is 2023.9.18.**460** and in the generated game project needs to be upgraded. to **537**. Once I upgrade that via Visual Studio, the game started running but crashed with this:

```
System.MissingFieldException: Field not found: 'FlatRedBall.Graphics.RenderBreak.ObjectCausingBreak'.
   at FlatRedBall.Gum.GumIdb.Draw(Camera camera)
   at FlatRedBall.Graphics.Renderer.DrawMixed(SpriteList spriteListUnfiltered, SortType sortType, PositionedObjectList`1 textListUnfiltered, List`1 batches, Boolean relativeToCamera, Camera camera, Section section)
   at FlatRedBall.Graphics.Renderer.DrawOrderedByDistanceFromCamera(Camera camera, Section section)
   at FlatRedBall.Graphics.Renderer.DrawUnlayeredObjects(Camera camera, RenderMode renderMode, Section section)
   at FlatRedBall.Graphics.Renderer.DrawCamera(Camera camera, RenderMode renderMode, Section section)
   at FlatRedBall.Graphics.Renderer.Draw(Section section)
   at FlatRedBall.FlatRedBallServices.RenderAll(Section section)
   at FlatRedBall.FlatRedBallServices.Draw(Section section)
   at MyProject.Game1.Draw(GameTime gameTime) in C:\Code\Fun\FlatRedBall\Projects\MyProject\MyProject\Game1.cs:line 86
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at MyProject.Program.Main(String[] args) in C:\Code\Fun\FlatRedBall\Projects\MyProject\MyProject\Program.cs:line 25
```

**Comment by vchelaru** [comment]
The second issue is fixed if you do a manual upgrade. I'm working on fixing the first issue now.

**Comment by vchelaru** [comment]
Fixed!
4b378933a4c3590460f91bca3f9485dff4793bed
