### ISSUE TITLE
Changing IncludeIIVisible should not cause an exception

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1267]
Can we dynamically adjust?

```
6:38:18 PM - System.MemberAccessException: LateBinder could not find a field or property by the name of IncludeInIVisible in the class FlatRedBall.Math.Geometry.Circle.  Check the name of the property to verify if it is correct.
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 510
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\GitHub\KidDefense\GameProject\KidDefense\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 495
   at GlueControl.Editing.VariableAssignmentLogic.SetVariable(GlueVariableSetData data, PositionedObject forcedItem) in C:\Users\vchel\Documents\GitHub\KidDefense\GameProject\KidDefense\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 210
GlueVariableSetData:
{
  "AssignOrRecordOnly": 0,
  "InstanceOwnerGameType": "KidDefense.Entities.Player",
  "VariableName": "this.OffsetCircleForCameraTarget.IncludeInIVisible",
  "VariableValue": "False",
  "Type": "System.Boolean",
  "IsState": false,
  "AbsoluteGlueProjectFilePath": "C:/Users/vchel/Documents/GitHub/KidDefense/GameProject/KidDefense/KidDefense.gluj",
  "ScreenSave": null,
  "EntitySave": null,
  "NamedObjectsToUpdate": []
}
```

**Comment by vchelaru** [comment]
This property was no longer used and is a holdover from long ago when IVisible visibility wasn't hierarchical. Removed completely from FRB.
