### ISSUE TITLE
Built-in plugin shuts down if Windows returns an error when attempting to hook a dead process

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#131]
```
---------------------------

---------------------------
A plugin has had an error.
Shutting down the plugin Global ContentManager Helper Plugin version 1.0 at file location
C:/Users/chris/source/Repos/FlatRedBall/FRBDK/Glue/Glue/bin/x86/Debug/netcoreapp3.0/Plugins\OfficialPlugins/OfficialPluginsCore.dll

Additional information:

System.ComponentModel.Win32Exception (5): Access is denied.

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)

   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)

   at System.Diagnostics.Process.GetOrOpenProcessHandle()

   at System.Diagnostics.Process.EnsureWatchingForExit()

   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)

   at OfficialPlugins.Compiler.Runner.HandleTimerTick(Object sender, EventArgs e) in C:\Users\chris\source\Repos\FlatRedBall\FRBDK\Glue\OfficialPlugins\Compiler\Runner.cs:line 94

   at System.Windows.Forms.Timer.OnTick(EventArgs e)

   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
OK   
---------------------------
```

This was caused by the existence of a dead process instance of my game executable, being held by another program. Since the process was in an invalid state, Windows stated that there was no access allowed to it for hooking onto process exit.

**Comment by vchelaru** [comment]
I believe this has been fixed in the new GlueView. That code has been re-written almost completely in the latest version of Glue.
