### ISSUE TITLE
Circle on entity is having its rotation set to NaN

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1431]
repro steps:
https://github.com/treesgobark/ShiftRpg/tree/bug/circleRotationNaN
https://github.com/vchelaru/FlatRedBall/assets/6179393/62254c8b-3739-4580-895d-e73fa3d6df8c
It's important to make sure the player is centered on the screen, so get away from the edges of the map. Get the mouse to the exact center of the point the gun is rotating around. Also you probably want to put a breakpoint on line 834 of PositionedObject. The bug seems to be related to the GameplayCenter circle object on Player as that's the object whose matrix has NaN values. You should note the attachments happening in `Player.InitializeChildren()`.

```
System.Exception: Error looping through AutomaticallyUpdatedSprites.  i is 10, cached count is 14 .  Actual count is 14 : The translation on the matrix is not 0.  It is {X:NaN Y:NaN Z:0}
 ---> System.ArgumentException: The translation on the matrix is not 0.  It is {X:NaN Y:NaN Z:0}
   at FlatRedBall.PositionedObject.set_RotationMatrix(Matrix value) in R:\Repositories\FRB\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\PositionedObject.cs:line 834
   at FlatRedBall.PositionedObject.UpdateDependencies(Double currentTime) in R:\Repositories\FRB\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\PositionedObject.cs:line 2068
   at FlatRedBall.PositionedObject.UpdateDependencies(Double currentTime) in R:\Repositories\FRB\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\PositionedObject.cs:line 2049
   at FlatRedBall.SpriteManager.UpdateDependencies() in R:\Repositories\FRB\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\SpriteManager.cs:line 3201
   --- End of inner exception stack trace ---
   at FlatRedBall.SpriteManager.UpdateDependencies() in R:\Repositories\FRB\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\SpriteManager.cs:line 3210
   at FlatRedBall.FlatRedBallServices.UpdateDependencies() in R:\Repositories\FRB\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1496
   at FlatRedBall.FlatRedBallServices.Draw(Section section) in R:\Repositories\FRB\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1411
   at FlatRedBall.FlatRedBallServices.Draw() in R:\Repositories\FRB\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1388
   at ProjectLoot.Game1.Draw(GameTime gameTime) in R:\Repositories\FRB\ProjectLoot\ProjectLoot\Game1.cs:line 64
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at ProjectLoot.Program.Main(String[] args) in R:\Repositories\FRB\ProjectLoot\ProjectLoot\Program.cs:line 35
```

**Comment by treesgobark** [comment]
Added NaN checks to inputs and rotations fdeac71f010f618a8ff8dac375e5adedad53bf16
