### ISSUE TITLE
Live Edit Functionality

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1457]
This issue lists all live edit functionality which is expected to work, will never work (with explanation) and things to do. For this card, the term "dynamic" refers to something that has been created while live edit was running. Dynamic objects will not have codegen available, so they must be handled by the editor. For example, if the user adds a new CircleInstance to an entity, that is a dynamic object.

## Startup

- [x] Starting the game in edit mode when nothing is selected, right when FRB launches should select the current screen

## Display

- [x] The Live Edit window should fill all available space in Glue - see https://docs.flatredball.com/flatredball/glue-reference/enable-live-edit/render-targets

## Screens

- [x] Pressing delete when an entity instance is selected in a screen list should delete the instance.

## Entities

- [x] Copy/Paste of entire entity should allow editing the newly-created entity. I tried this with an entity that has a sprite and circle, but I could not select the circle in the new entity. In fact, the new entity would never show up.
- [x] Rename Entity should allow to continue editing the new entity and seeing the changes in live edit
- [x] Renaming Entity should properly use the new element including changes on the renamed element on existing (code generated) instances
- [x] Renaming Entity should properly use the new element on dynamic instances added before rename
- [x] Renaming Entity should properly use the new element on dynamic instances added after rename

## Files

- [x] Changing .achx should update relative frames immediately and relative positions

## Objects

- [x] Create new instances by drag+dropping
    - [x] Instances in an entity appear on instances of that entity in a screen
- [x] Create new instances by copy/paste
- [x] Editing points on an existing polygon by drag+moving should apply to polygon Glue JSON 
- [x] Editing points on an existing polygon by drag+moving should apply to instances of the entity that contains the polygon
- [x] Adding dynamic polygon to entity and editing the points should apply to instances of the entity that contains the polygon
- [x] Adding a dynamic polygon to an entity, adding an instance of that to the screen, then deleting the instance should delete the polygon. This works if no changes are made to the points, but if we make it a rectangle, resize points, deselect the entity (unload it) then reload it, deleting does not remove the polygon.
- [x] Adding instance, making changes to the instance, renaming instance, make more changes to the instance. Deselect/reselect screen that contains instance should show all changes that were made before and after the rename.

## Variables

- [x] Assign existing variables on objects
- [x] Create new tunneled variable
- [x] Create new tunneled variable which displays as absolute (X, Y, Z, RotationZ), but modifies relative values (RelativeX, RelativeY, RelativeZ, RotationZ)
- [x] Tunneled variables can be set on instances of the entity that has the tunneled variable
- [x] Create dynamic non-tunneled variables - These won't do anything in game until the game is rebuilt, but there's no reason to stop the game when it's created.
- [x] Dynamic non-tunneled variables should be assignable on instances
- [x] Dynamic entity, dynamic sprite (created in initial popup), add texture, tunnel Sprite Alpha, change sprite alpha should update on entity preview. Works fine after restart.
- [x] Dynamic entity, dynamic sprite, add texture, tunnel sprite alpha. Create instances of the entity in a screen, set sprite alpha at the screen level. Go back to entity level and change alpha. The changes at the NOS level should not apply on the instances that have set the variable at the instance level.

## States and Categories

- [x] Including an existing variable to a state should allow previewing that state by changing its value
- [x] Adding included variables on a category should show up when previewing the state
- [x] Including a dynamic variable on dynamic object then assigning this on a state should allow previewing in the entity
- [x] Including a dynamic variable on dynamic object then assigning this on a state should show up on instances. This ultimately requires being able to apply states dynamically rather than through codegen. Adding this as a feature...
- [x] Create a new category, add new states to the category, modify the states, add a new variable to the entity of type state, set the new variable on instances of the entity, the state should show
- [x] Make default on dynamic state in dynamic entity with dynamic variable assignments results in exception:
```cs
System.MemberAccessException: LateBinder could not find a field or property by the name of CurrentSizeCategoryState in the class LiveEditTest.Entities.SpriteEntity.  Check the name of the property to verify if it is correct.
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\Owner\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 510
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\Owner\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\Owner\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\Owner\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 676
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\Owner\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 603
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(String variableName, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\Owner\Documents\FlatRedBallProjects\LiveEditTest\LiveEditTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 317
String:
"this.SpriteEntity1.CurrentSizeCategoryState="
```

### Known not implemented
- [ ] Adding excluded variables on a category should show up when previewing the state - this currently requires a restart because it would take a bit of work to detect if a state already had a value compiled in

**Comment by profexorgeek** [comment]
The Live Edit portion doesn't always fill the entire available space in Glue as demonstrated here. This is reproduceable in Nardiak and I _think_ it has to do with the game's resolution settings because the rendered portion is the same size as the resolution the game runs at. Glue should override the game's max resolution when displaying within Glue.

![image](https://github.com/user-attachments/assets/a07c8c4e-e839-482d-97e3-d734a4166301)

**Comment by vchelaru** [comment]
As mentioned in the original description, this was caused by using a render target. More info here: https://docs.flatredball.com/flatredball/glue-reference/enable-live-edit/render-targets
