### ISSUE TITLE
Live Editor should handle creation of an entity variable more gracefully

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1473]
**Expected result:** I can create a new variable on an entity class, then switch to a screen and set a value for that variable on an entity instance.

**Actual result:** Everything appears to work but glue throws errors in the output window and data may be lost

**Expected change:** Glue doesn't have to support doing all this in live edit mode but we should strive for zero cases where the user can lose work due to a bad editor state. I'm not sure if work is lost but there is desynchronization between Glue and the game representation.

**Details**
If you create a new variable on an entity while live edit is running, then switch to a screen and set a value on that variable, Glue throws errors. Here's what I did while Live Edit was running (I think you can repro this in a new project)...

1. Created a `string` variable on a monster spawner entity called `ZoneName`
2. Switched to my `Dungeon1` test screen and clicked on a monster spawner instance
3. Set the `ZoneName` property on that instance to `Zone1`
4. Glue threw the error below

```
10:08:59 AM - System.MemberAccessException: LateBinder could not find a field or property by the name of ZoneName in the class Nardiak.Entities.World.Markers.MonsterSpawner.  Check the name of the property to verify if it is correct.
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 510
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 675
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\jusjohns\Documents\projects\Nardiak\Nardiak\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 549
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(String variableName, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\jusjohns\Documents\projects\Nardiak\Nardiak\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 305
String:
"this.MonsterSpawner1.ZoneName=Zone1"
```

**Comment by vchelaru** [comment]
This has been fixed. I actually wasn't able to reproduce the problem exactly as-is, but I did find an issue causing restarts that wasn't necessary so I fixed that. I believe this should work now.
