### ISSUE TITLE
Toggling IncludeInICollidable should be handled by GlueView

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#161]
```
System.MemberAccessException: LateBinder could not find a field or property by the name of IncludeInICollidable in the class FlatRedBall.Math.Geometry.Circle.  Check the name of the property to verify if it is correct.
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 485
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 353
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 622
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 597
   at GlueControl.Editing.VariableAssignmentLogic.SetVariable(GlueVariableSetData data, PositionedObject forcedItem) in C:\Users\vchel\Documents\FlatRedBallProjects\GView2Test\GView2Test\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 74
Restarting because: Unhandled variable IncludeInICollidable changed
```

**Comment by vchelaru** [comment]
Fixed: be656122c873af58bcb73066d51d6c166a8437e3
