### ISSUE TITLE
[FNASubmodule fork] Error on standard platformer creation

### ISSUE THREAD

**Issue by ValorZard** [vchelaru/FlatRedBall#1637]
(Currently, you have to manually go in and select the FNA template)
```Gum Plugin (2.4.2):Gum Plugin Version 2.4.2 Failed in CallPluginMethod CreateGumProjectWithForms
Plugin also failed during shutdown
C:/Github/FlatRedBall/FRBDK/Glue/Glue/bin/Debug/Plugins/GumPlugin/GumPlugin.dll
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'Plugins/GumPlugin/Tools/GumProjectFontGenerator/GumProjectFontGenerator.exe' with working directory 'C:\Github\FlatRedBall\FRBDK\Glue\Glue\bin\Debug'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GumPlugin.MainGumPlugin.<>c__DisplayClass37_0.<<HandleBuildMissingFonts>b__0>d.MoveNext() in C:\Github\FlatRedBall\FRBDK\Glue\GumPlugin\GumPlugin\MainGumPlugin.cs:line 850
--- End of stack trace from previous location ---
   at FlatRedBall.Glue.Tasks.GlueAsyncTask.Do_Action_Internal() in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Tasks\GlueTask.cs:line 114
   at FlatRedBall.Glue.Managers.TaskManager.RunTask(GlueTaskBase task, Boolean markAsCurrent) in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Tasks\TaskManager.cs:line 369
   at FlatRedBall.Glue.Managers.TaskManager.AddOrRunIfTasked(Func`1 func, String displayInfo, TaskExecutionPreference executionPreference, Boolean doOnUiThread) in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Tasks\TaskManager.cs:line 535
   at FlatRedBall.Glue.Managers.TaskManager.AddAsync(Func`1 func, String displayInfo, TaskExecutionPreference executionPreference, Boolean doOnUiThread) in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Tasks\TaskManager.cs:line 485
   at GumPlugin.MainGumPlugin.HandleBuildMissingFonts() in C:\Github\FlatRedBall\FRBDK\Glue\GumPlugin\GumPlugin\MainGumPlugin.cs:line 794
   at GumPlugin.Managers.NewGumProjectCreationLogic.<>c__DisplayClass3_0.<<CreateGumProjectInternal>b__0>d.MoveNext() in C:\Github\FlatRedBall\FRBDK\Glue\GumPlugin\GumPlugin\Managers\NewGumProjectCreationLogic.cs:line 97
--- End of stack trace from previous location ---
   at FlatRedBall.Glue.Tasks.GlueAsyncTask.Do_Action_Internal() in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Tasks\GlueTask.cs:line 114
   at FlatRedBall.Glue.Managers.TaskManager.RunTask(GlueTaskBase task, Boolean markAsCurrent) in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Tasks\TaskManager.cs:line 369
   at FlatRedBall.Glue.Managers.TaskManager.AddOrRunIfTasked(Func`1 func, String displayInfo, TaskExecutionPreference executionPreference, Boolean doOnUiThread) in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Tasks\TaskManager.cs:line 535
   at FlatRedBall.Glue.Managers.TaskManager.AddAsync(Func`1 func, String displayInfo, TaskExecutionPreference executionPreference, Boolean doOnUiThread) in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Tasks\TaskManager.cs:line 485
   at GumPlugin.Managers.NewGumProjectCreationLogic.CreateGumProjectInternal(Boolean shouldAlsoAddForms, Boolean askToOverwrite) in C:\Github\FlatRedBall\FRBDK\Glue\GumPlugin\GumPlugin\Managers\NewGumProjectCreationLogic.cs:line 63
   at GumPlugin.MainGumPlugin.CreateGumProjectWithForms(Boolean askToOverwrite) in C:\Github\FlatRedBall\FRBDK\Glue\GumPlugin\GumPlugin\MainGumPlugin.cs:line 750
   at FlatRedBall.Glue.Plugins.PluginManager.<>c__DisplayClass48_0.<<CallPluginMethodAsync>b__0>d.MoveNext() in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Plugins\PluginManager.cs:line 703
--- End of stack trace from previous location ---
   at FlatRedBall.Glue.Plugins.PluginManager.PluginCommand(Func`1 func, PluginContainer container, String message) in C:\Github\FlatRedBall\FRBDK\Glue\Glue\Plugins\PluginManager.cs:line 1990
Missing SourceFile for GameScreenGumRuntime GumScreen in Screens\GameScreen (Screen) : gumproject/Screens/GameScreenGum.gusx
```

And it doesn't work when you try to run in the editor

```Nuget Restore succeeded at 4:07:03 PM in (00:00:02.985)
Build started at 4:07:03 PM
C:\Users\sraya\OneDrive\Documents\FlatRedBallProjects\another_one\another_one\Screens\GameScreen.Generated.cs(48,17): error CS0246: The type or namespace name 'GameScreenGumRuntime' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\sraya\OneDrive\Documents\FlatRedBallProjects\another_one\another_one\another_one.csproj]```

**Comment by vchelaru** [comment]
I believe this has been fixed by https://github.com/vchelaru/FlatRedBall/commit/33cfbc04c9a6068de8c28b08827ecbbc14ef9c6f
