### ISSUE TITLE
crash when adding a glue variable in edit mode

### ISSUE THREAD

**Issue by dantogno** [vchelaru/FlatRedBall#226]
---------------------------

---------------------------
A plugin has had an error.
Shutting down the plugin Global ContentManager Helper Plugin version 1.0 at file location
D:/GitHub/FlatRedBall/FRBDK/Glue/Glue/bin/x86/Debug/netcoreapp3.0/Plugins\OfficialPlugins/OfficialPluginsCore.dll

Additional information:

System.InvalidOperationException: Cross-thread operation not valid: Control 'ElementTreeView' accessed from a thread other than the thread it was created on.

   at System.Windows.Forms.Control.get_Handle()

   at System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, Int32 lparam)

   at System.Windows.Forms.TreeView.get_SelectedNode()

   at FlatRedBall.Glue.EditorLogic.get_CurrentEntitySave() in D:\GitHub\FlatRedBall\FRBDK\Glue\Glue\EditorLogic.cs:line 162

   at FlatRedBall.Glue.Plugins.ExportedImplementations.GlueState.get_CurrentEntitySave() in D:\GitHub\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\GlueState.cs:line 75

   at OfficialPlugins.Compiler.MainPlugin.HandleCompilerViewModelPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\GitHub\FlatRedBall\FRBDK\Glue\OfficialPlugins\Compiler\MainPlugin.cs:line 546

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)

   at System.Threading.QueueUserWorkItemCallback.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
OK   
---------------------------

**Comment by vchelaru** [comment]
I couldn't reproduce this, but I did refactor out EditorLogic to help solve problems like this in the future.
