### ISSUE TITLE
Glue should not crash when adding multiple files to GlobalContent

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#284]
Steps I took:

1. GlobalContent has a folder called ParmeEmitters but no files are in the folder in Glue
2. Add Files Dialog > Browser
3. Select all files in the ParmeEmitters folder (same folder Glue points to)
4. Glue crashes

Two different crash dialogs popped up.

**First Dialog**
```
---------------------------

---------------------------
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   at System.Collections.Generic.List`1.Enumerator.MoveNext()

   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)

   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

   at FlatRedBall.Glue.Managers.AddExistingFileManager.AddExistingFileClick() in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Managers\AddExistingFileManager.cs:line 51

   at FlatRedBall.Glue.FormHelpers.RightClickHelper.<>c.<Initialize>b__48_4(Object not, EventArgs used) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\FormHelpers\RightClickHelper.cs:line 1194

   at OfficialPlugins.TreeViewPlugin.Views.MainTreeViewControl.<>c__DisplayClass14_1.<CreateWpfItemFor>b__0(Object not, RoutedEventArgs used) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\OfficialPlugins\TreeViewPlugin\Views\MainTreeViewControl.xaml.cs:line 211

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)

   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location where exception was thrown ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)

   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.Run(Form mainForm)

   at Glue.Program.Main() in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Program.cs:line 46
---------------------------
OK   
---------------------------
```

**Second Dialog**
```
---------------------------

---------------------------
A plugin has had an error.
Shutting down the plugin Global ContentManager Helper Plugin version 1.0 at file location
C:/Users/jusjohns/Documents/projects/FlatRedBall/FRBDK/Glue/Glue/bin/x86/Debug/netcoreapp3.0/Plugins\OfficialPlugins/OfficialPluginsCore.dll

Additional information:

System.ComponentModel.InvalidAsynchronousStateException: An error occurred invoking the method.  The destination thread no longer exists.

   at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)

   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)

   at System.Windows.Forms.Control.Invoke(Delegate method)

   at FlatRedBall.Glue.Plugins.PluginManager.PluginCommand(Action action, PluginContainer container, String message) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\PluginManager.cs:line 1879

   at FlatRedBall.Glue.Plugins.PluginManager.GetIfUsesContentPipeline(String fileAbsolute) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\PluginManager.cs:line 1944

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.ProjectCommands.GetIfShouldUseContentPipeline(String fileAbsolute) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\ProjectCommands.cs:line 344

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.ProjectCommands.UpdateFileMembershipInProject(VisualStudioProject project, String fileName, Boolean useContentPipeline, Boolean shouldLink, String parentFile, Boolean recursive, List`1 alreadyReferencedFiles) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\ProjectCommands.cs:line 200

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.ProjectCommands.UpdateFileMembershipInProject(ReferencedFileSave referencedFileSave) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\ProjectCommands.cs:line 157

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.GluxCommands.AddReferencedFileToGlobalContent(ReferencedFileSave referencedFileSave) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\GluxCommands.cs:line 415

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.GluxCommands.AddReferencedFileToGlobalContent(String fileToAdd, Boolean useFullPathAsName) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\GluxCommands.cs:line 400

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.GluxCommands.CreateReferencedFileSaveForExistingFile(IElement containerForFile, String directoryInsideContainer, String absoluteFileName, PromptHandleEnum unknownTypeHandle, AssetTypeInfo ati, String& creationReport, String& errorMessage, Boolean selectFileAfterCreation) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\GluxCommands.cs:line 684

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.GluxCommands.AddSingleFileTo(String fileName, String rfsName, String extraCommandLineArguments, BuildToolAssociation buildToolAssociation, Boolean isBuiltFile, Object options, GlueElement sourceElement, String directoryOfTreeNode, Boolean selectFileAfterCreation) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\GluxCommands.cs:line 499

   at FlatRedBall.Glue.Managers.AddExistingFileManager.AddSingleFile(FilePath fileName, Boolean& userCancelled, IElement element, String directoryOfTreeNode, Object options) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Managers\AddExistingFileManager.cs:line 143

   at FlatRedBall.Glue.Managers.AddExistingFileManager.<>c__DisplayClass0_1.<AddExistingFileClick>b__2() in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Managers\AddExistingFileManager.cs:line 60

   at FlatRedBall.Glue.Managers.TaskManager.<>c__DisplayClass34_0.<ProcessNextSync>b__0(Object <p0>) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Tasks\TaskManager.cs:line 410

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)

   at System.Threading.QueueUserWorkItemCallback.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
OK   
---------------------------

```

**Comment by vchelaru** [comment]
Fixed.

cfc32bbd9cdb0b7d441524b5b5d99ea55eecde71
