### ISSUE TITLE
Glue should not crash when creating new project templates

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#339]
I am fully updated as of the time of this issue filing and am running tools from src. I attempted to create a new GL project, used the Wizard, and chose the UI (FRB.Forms) project. Glue crashed:

![image](https://user-images.githubusercontent.com/711100/148665067-2608a568-6d39-465a-a2ad-f55ff7cd53cc.png)

Stack trace:
```
---------------------------

---------------------------
A plugin has had an error.
Shutting down the plugin Gum Plugin version 2.4.1 at file location
C:/Users/jusjohns/Documents/projects/FlatRedBall/FRBDK/Glue/Glue/bin/x86/Debug/netcoreapp3.0/Plugins\GumPlugin/GumPluginCore.dll

Additional information:

System.NullReferenceException: Object reference not set to an instance of an object.

   at GumPlugin.Managers.GumProjectManager.TryAddNewGumProject() in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\GumPlugin\GumPlugin\Managers\GumProjectManager.cs:line 88

   at GumPlugin.MainPlugin.<>c__DisplayClass36_0.<CreateGumProjectInternal>b__0() in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\GumPlugin\GumPlugin\MainPlugin.cs:line 740

   at FlatRedBall.Glue.Managers.TaskManager.<>c__DisplayClass35_0.<ProcessNextSync>b__0(Object <p0>) in C:\Users\jusjohns\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Tasks\TaskManager.cs:line 417

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)

   at System.Threading.QueueUserWorkItemCallback.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
OK   
---------------------------

```

**Comment by vchelaru** [comment]
Project wasn't rebuilt. Had to pull Gum and rebuild Glue with all.sln
