### ISSUE TITLE
Game Crash (edit mode) when dragging entity instance onto collision

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#357]
1. Create a collidable entity and make sure you have a list of them in the GameScreen
2. Create a level, and verify that the list of that entity shows up in the new level
3. Verify you have Solid collision (this is default from most wizard configurations)
4. Add an instance of the collidable entity to the list in your Level1
5. Run the game in edit mode
6. Drag+drop the instance from the list onto the SolidCollision while the game is running

Observe an error message:

```
---------------------------

---------------------------
The game has crashed:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at GlueControl.Editing.VariableAssignmentLogic.<GetDesiredRelationshipType>g__GetStandardCollisionRelationshipType|9_1(<>c__DisplayClass9_0& ) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 835

   at GlueControl.Editing.VariableAssignmentLogic.GetDesiredRelationshipType(NamedObjectSave namedObject, Object& firstObject, Object& secondObject) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 854

   at GlueControl.InstanceLogic.TryCreateCollisionRelationship(NamedObjectSave deserialized) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\InstanceLogic.Generated.cs:line 347

   at GlueControl.InstanceLogic.HandleCreateInstanceCommandFromGlueInner(NamedObjectSave deserialized, Int32 currentAddObjectIndex, PositionedObject owner) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\InstanceLogic.Generated.cs:line 158

   at GlueControl.InstanceLogic.HandleCreateInstanceCommandFromGlue(AddObjectDto dto, Int32 currentAddObjectIndex, PositionedObject forcedItem) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\InstanceLogic.Generated.cs:line 131

   at GlueControl.CommandReceiver.HandleDto(AddObjectDto dto) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\CommandReceiver.Generated.cs:line 512

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

   at GlueControl.CommandReceiver.ReceiveDto(Object dto) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\CommandReceiver.Generated.cs:line 105

   at GlueControl.CommandReceiver.Receive(String message, Func`2 runPredicate) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\CommandReceiver.Generated.cs:line 79

   at GlueControl.GlueControlManager.ApplySetMessage(String message) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\GlueControlManager.Generated.cs:line 312

   at GlueControl.GlueControlManager.<>c__DisplayClass21_0.<ProcessMessage>b__0() in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\GlueControl\GlueControlManager.Generated.cs:line 298

   at FlatRedBall.Instructions.InstructionManager.<>c__DisplayClass31_0.<DoOnMainThreadAsync>b__0() in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\InstructionManager.cs:line 157

   at FlatRedBall.Instructions.DelegateInstruction.Execute() in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\DelegateInstruction.cs:line 45

   at FlatRedBall.Instructions.InstructionManager.Update() in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\InstructionManager.cs:line 715

   at FlatRedBall.FlatRedBallServices.Update(GameTime gameTime, Section section) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1300

   at FlatRedBall.FlatRedBallServices.Update(GameTime gameTime) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1277

   at MenuTest.Game1.Update(GameTime gameTime) in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\Game1.cs:line 97

   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)

   at Microsoft.Xna.Framework.Game.Tick()

   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()

   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)

   at Microsoft.Xna.Framework.Game.Run()

   at MenuTest.Program.Main() in c:\users\vchel\documents\flatredballprojects\menutest\MenuTest\Program.cs:line 20
---------------------------
OK   
---------------------------
```

Expeted: no error message

**Comment by vchelaru** [comment]
Fixed.

e9a514723b81f210a75335f792b5cd131e84fc15
