### ISSUE TITLE
Game crashes when switching from some entities to others in edit mode

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#359]
I'm not sure if this is something FRB is doing or if it's specific to the game I'm working on, but I'm logging it here in case it is a FRB bug.

![image](https://user-images.githubusercontent.com/729631/150645905-2b1a77ab-1afb-4e6b-9ba8-a5d276cb848a.png)

Error text:

```
---------------------------

---------------------------
The game has crashed:

System.Exception: The Screen that was just unloaded (EntityViewingScreen) did not clean up after itself:
There are 12 AutomaticallyUpdatedSprites in the SpriteManager. See "FlatRedBall.SpriteManager.AutomaticallyUpdatedSprites"
There are 12 Ordered (Drawn) Sprites in the SpriteManager.  See "FlatRedBall.SpriteManager.OrderedSprites"
There are 12 Managed PositionedObjects in the SpriteManager.  See "FlatRedBall.SpriteManager.ManagedPositionedObjects"
The first is an unnnamed entity of type ScreenXEdgeToEdgeArcEnemy
There are 12 Automatically Updated Shapes in the ShapeManager.  See "FlatRedBall.Math.Geometry.ShapeManager.AutomaticallyUpdatedShapes"
There are 12 visible Circles in the ShapeManager.  See "FlatRedBall.Math.Geometry.ShapeManager.VisibleCircles"

   at FlatRedBall.Screens.ScreenManager.CheckAndWarnIfNotEmpty(Screen screen) in c:\users\vchel\documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\ScreenManager.cs:line 863

   at FlatRedBall.Screens.ScreenManager.Activity() in c:\users\vchel\documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\ScreenManager.cs:line 236

   at CrankyChibiCthulu.Game1.Update(GameTime gameTime) in c:\users\vchel\documents\github\kimuzukash-chibi-kuto-urufu\crankychibicthulu\Game1.cs:line 100

   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)

   at Microsoft.Xna.Framework.Game.Tick()

   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()

   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)

   at Microsoft.Xna.Framework.Game.Run()

   at CrankyChibiCthulu.Program.Main() in c:\users\vchel\documents\github\kimuzukash-chibi-kuto-urufu\crankychibicthulu\Program.cs:line 20
---------------------------
OK   
---------------------------

```

**Comment by vchelaru** [comment]
This is caused by starting in edit mode. When this happens, the startup level is first loaded, then the game quickly switches to the entity viewing screen.

There are actually 2 bugs here:

1. There's something that is leftover in the first screen which causes the crash
2. The game should just go directly to the entity viewing screen as that would be much faster in many cases.

Fixing # 1 is hard because I can't get it to happen with a debugger attached, so I'm going to focus on  # 2

**Comment by vchelaru** [comment]
Fixed.
b05e2ba8bfa1ff8d0ac85a72a9ebda1486a568ac
