### ISSUE TITLE
Crash on creating new top down project

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#461]
Error:

```
1:17:43 PM - Could not find the CSV file C:/Users/vchel/Documents/FlatRedBallProjects/Snorvarg2/Snorvarg2/Content/Entities/Player/TopDownValuesStatic.csv when trying to generate a data file
1:17:45 PM - System.IO.FileNotFoundException: Could not find the file C:/Users/vchel/Documents/FlatRedBallProjects/Snorvarg2/Snorvarg2/Content/Entities/Player/TopDownValuesStatic.csv or the directory C:/Users/vchel/Documents/FlatRedBallProjects/Snorvarg2/Snorvarg2/Content/Entities/Player/
File name: 'C:/Users/vchel/Documents/FlatRedBallProjects/Snorvarg2/Snorvarg2/Content/Entities/Player/TopDownValuesStatic.csv'
   at FlatRedBall.IO.FileManager.ThrowExceptionIfFileDoesntExist(String fileName) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\IO\FileManager.cs:line 1382
   at FlatRedBall.IO.Csv.CsvFileManager.CsvDeserializeToRuntime[T](String fileName) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\IO\Csv\CsvFileManager.cs:line 95
   at FlatRedBall.IO.Csv.CsvFileManager.CsvDeserializeToRuntime(String fileName) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\IO\Csv\CsvFileManager.cs:line 81
   at FlatRedBall.Glue.CsvCodeGenerator.DeserializeToRcr(AvailableDelimiters delimiter, String fileName, RuntimeCsvRepresentation& rcr, Boolean& succeeded) in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\Glue\Glue\Parsing\CsvCodeGenerator.cs:line 467
```

**Comment by vchelaru** [comment]
Fixed

f42ac585ce91142ce070d99fff3857768dd9b358
