### ISSUE TITLE
Drag+drop of state onto editor view causes crash - it should not

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#467]
I believe this worked at one point, so something must have changed with the types. This happens with the acorn object in SuperBounceHouse.

Error:

```
---------------------------

---------------------------
The game has crashed:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error trying to set field GroundMovement which is of type SuperBounceHouse.DataTypes.PlatformerValues.
Trying to set to Flying in PlatformerValuesStatic.csv of type System.String

   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetField(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 416

   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 347

   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52

   at GlueControl.InstanceLogic.AssignVariable(Object instance, InstructionSave instruction) in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\GlueControl\InstanceLogic.Generated.cs:line 1116

   at GlueControl.CommandReceiver.ReplaceStateWithNewState(String elementGameType, String categoryName, StateSave newStateSave) in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\GlueControl\CommandReceiver.Generated.cs:line 502

   at GlueControl.CommandReceiver.HandleDto(ChangeStateVariableDto dto) in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\GlueControl\CommandReceiver.Generated.cs:line 188

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

   at GlueControl.CommandReceiver.ReceiveDto(Object dto) in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\GlueControl\CommandReceiver.Generated.cs:line 105

   at GlueControl.CommandReceiver.Receive(String message, Func`2 runPredicate) in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\GlueControl\CommandReceiver.Generated.cs:line 79

   at GlueControl.GlueControlManager.ApplySetMessage(String message) in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\GlueControl\GlueControlManager.Generated.cs:line 229

   at GlueControl.GlueControlManager.<>c__DisplayClass14_0.<ProcessMessage>b__0() in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\GlueControl\GlueControlManager.Generated.cs:line 215

   at FlatRedBall.Instructions.InstructionManager.<>c__DisplayClass31_0.<DoOnMainThreadAsync>b__0() in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\InstructionManager.cs:line 157

   at FlatRedBall.Instructions.DelegateInstruction.Execute() in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\DelegateInstruction.cs:line 45

   at FlatRedBall.Instructions.InstructionManager.Update() in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\InstructionManager.cs:line 715

   at FlatRedBall.FlatRedBallServices.Update(GameTime gameTime, Section section) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1300

   at FlatRedBall.FlatRedBallServices.Update(GameTime gameTime) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1277

   at SuperBounceHouse.Game1.Update(GameTime gameTime) in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\Game1.cs:line 98

   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)

   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)

   at Microsoft.Xna.Framework.Game.Run()

   at SuperBounceHouse.Program.Main() in c:\users\vchel\documents\github\superbouncehouse\SuperBounceHouse\Program.cs:line 20
---------------------------
OK   
---------------------------

```

**Comment by vchelaru** [comment]
I cannot get this to reproduce, so I've added more diagnostic info:

1dc03e3cf22879a4800fe508af282726863e57b8

We'll see if it comes up again and what the diagnostics say.

**Comment by vchelaru** [comment]
This may have been fixed here

36c86df0ba4a595e9d75319177488de833bb90fe

I've added more diagnostics, so we'll see if it's solved. If a week or two pass without a crash, this can probably be closed.

**Comment by vchelaru** [comment]
Update - I believe I have a crash occurring consistently when doing drag+move copy/paste (pasting without letting go). Need to investigate more ...

**Comment by vchelaru** [comment]
I believe this has been fixed with the latest changes. Closing, and will reopen with callstack if it happens again.
