### ISSUE TITLE
Crash adding new platformer movement values

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#472]
```
---------------------------

---------------------------
The game has crashed:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at FlatRedBall.IO.Csv.RuntimeCsvRepresentation.UpdateValues[KeyType,ValueType](Dictionary`2 dictionaryToUpdate, String contentManagerName) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\IO\Csv\RuntimeCsvRepresentation.cs:line 803

   at FlatRedBall.IO.Csv.CsvFileManager.UpdateDictionaryValuesFromCsv[KeyType,ValueType](Dictionary`2 dictionaryToUpdate, String fileName) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\IO\Csv\CsvFileManager.cs:line 69

   at FloatTest2.Entities.Player.Reload(Object whatToReload) in C:\Users\Owner\Documents\FlatRedBallProjects\FloatTest2\FloatTest2\Entities\Player.Generated.cs:line 407

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

   at GlueControl.CommandReceiver.HandleDto(ForceReloadFileDto dto) in C:\Users\Owner\Documents\FlatRedBallProjects\FloatTest2\FloatTest2\GlueControl\CommandReceiver.Generated.cs:line 852

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

   at GlueControl.CommandReceiver.ReceiveDto(Object dto) in C:\Users\Owner\Documents\FlatRedBallProjects\FloatTest2\FloatTest2\GlueControl\CommandReceiver.Generated.cs:line 105

   at GlueControl.CommandReceiver.Receive(String message, Func`2 runPredicate) in C:\Users\Owner\Documents\FlatRedBallProjects\FloatTest2\FloatTest2\GlueControl\CommandReceiver.Generated.cs:line 79

   at GlueControl.GlueControlManager.ApplySetMessage(String message) in C:\Users\Owner\Documents\FlatRedBallProjects\FloatTest2\FloatTest2\GlueControl\GlueControlManager.Generated.cs:line 298

   at GlueControl.GlueControlManager.<>c__DisplayClass21_0.<ProcessMessage>b__0() in C:\Users\Owner\Documents\FlatRedBallProjects\FloatTest2\FloatTest2\GlueControl\GlueControlManager.Generated.cs:line 284

   at FlatRedBall.Instructions.InstructionManager.<>c__DisplayClass31_0.<DoOnMainThreadAsync>b__0() in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\InstructionManager.cs:line 157

   at FlatRedBall.Instructions.DelegateInstruction.Execute() in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\DelegateInstruction.cs:line 45

   at FlatRedBall.Instructions.InstructionManager.Update() in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\InstructionManager.cs:line 715

   at FlatRedBall.FlatRedBallServices.Update(GameTime gameTime, Section section) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1300

   at FlatRedBall.FlatRedBallServices.Update(GameTime gameTime) in C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1277

   at FloatTest2.Game1.Update(GameTime gameTime) in C:\Users\Owner\Documents\FlatRedBallProjects\FloatTest2\FloatTest2\Game1.cs:line 71

   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)

   at Microsoft.Xna.Framework.Game.Tick()

   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()

   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)

   at Microsoft.Xna.Framework.Game.Run()

   at FloatTest2.Program.Main() in C:\Users\Owner\Documents\FlatRedBallProjects\FloatTest2\FloatTest2\Program.cs:line 20
---------------------------
OK   
---------------------------

```

**Comment by vchelaru** [comment]
Fixed.

0b2ae17726fa4a44dccaa49da4134ce94a8c4a45
