### ISSUE TITLE
Setting points on a polygon in live edit should not cause a crash

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#543]
This happens:

```
8:30:31 AM - System.InvalidOperationException: Attempting to set property Points of type System.Collections.Generic.IList`1[FlatRedBall.Math.Geometry.Point] to value System.Collections.Generic.List`1[Microsoft.Xna.Framework.Vector2] with type System.String
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 92
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 490
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 376
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 627
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\FlatRedBallProjects\ShiftZTest\ShiftZTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 334
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\FlatRedBallProjects\ShiftZTest\ShiftZTest\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 138
```

**Comment by vchelaru** [comment]
Fixed

d0361ff161603443b24876011ac900161dfda981
