### ISSUE TITLE
Glue should not crash when adding objects

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#55]
I don't have a lot of information on why this happens. Sometimes when I create a new entity type Glue crashes when I try to add objects to it. The entities that crash seem to:

1. Inherit from a base type
2. Have at least one object that is set by derived

**Gif:**
![glue-asplode](https://user-images.githubusercontent.com/711100/102939542-b0015980-446b-11eb-869b-035da28cf034.gif)

**Full Error:**
```
---------------------------

---------------------------
A plugin has had an error.
Shutting down the plugin Global ContentManager Helper Plugin version 1.0 at file location
C:/Users/justi/Documents/projects/FlatRedBall/FRBDK/Glue/Glue/bin/x86/Debug/netcoreapp3.0/Plugins\OfficialPlugins/OfficialPluginsCore.dll

Additional information:

System.NullReferenceException: Object reference not set to an instance of an object.

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.DialogCommands.CreateAndShowAddNamedObjectWindow(AddObjectViewModel& addObjectViewModel) in C:\Users\justi\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\DialogCommands.cs:line 68

   at FlatRedBall.Glue.Plugins.ExportedImplementations.CommandInterfaces.DialogCommands.ShowAddNewObjectDialog(AddObjectViewModel addObjectViewModel) in C:\Users\justi\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\Plugins\ExportedImplementations\CommandInterfaces\DialogCommands.cs:line 34

   at Glue.MainGlueWindow.addObjectToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\justi\Documents\projects\FlatRedBall\FRBDK\Glue\Glue\MainGlueWindow.cs:line 715

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)

   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
OK   
---------------------------
```

**Comment by vchelaru** [comment]
Fixed.
