### ISSUE TITLE
Glue should not fail to Expose In Derived

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#590]
I have a base class called `DecorBase`, which has a sprite. This class exposes a variety of variables to control rotation, color, etc so that decor items can be added to a screen and customized.

I have a new item called `Planet` that should extend `DecorBase` and the `SpriteInstance` owned by the parent class should be accessible in the child class. However, when I attempt to make the `SpriteInstance` ExposedInDerived Glue throws an error.

If something I'm doing is not allowed, it should be more clear what's wrong. Closing and repopening Glue resets the `ExposedInDerived` value to `false`.

![glue-expose-in-derived](https://user-images.githubusercontent.com/711100/172873686-20ba6f2e-4079-402a-8c7d-c0068f6c5413.gif)

**Comment by profexorgeek** [comment]
Error message:

8:33:49 AM - System.InvalidOperationException: The type FlatRedBall.Graphics.ColorOperation may not be used in this context.
   at System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(String name, String ns, Object o, Boolean xsiType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriter1.Write1_Object(String n, String ns, Object o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriter1.Write10_CustomVariableInNamedObject(String n, String ns, CustomVariableInNamedObject o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriter1.Write14_NamedObjectSave(String n, String ns, NamedObjectSave o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriter1.Write15_NamedObjectSave(Object o)
   at Microsoft.Xml.Serialization.GeneratedAssembly.NamedObjectSaveSerializer.Serialize(Object objectToSerialize, XmlSerializationWriter writer)
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)

**Comment by vchelaru** [comment]
Fixed

d9cd2b2e2195a1f4d59fe5d634475a138a5d3938
