### ISSUE TITLE
Editor should not throw errors when setting the animation chains on a sprite

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#625]
Repro steps:

1. Create a new entity with the editor running
2. Add a sprite to the entity (while in preview mode)
3. Add an ACHX to the entity files
4. Set the animation chain on the sprite you added

Expected result: the animation chain list is set and you can choose a specific animation from the list
Actual result: Glue freezes for a period of time and the error below appears in the output:

```
8:51:38 PM - System.InvalidOperationException: There is no animation named Wing001
This sprite has no animations
   at FlatRedBall.Sprite.set_CurrentChainName(String value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Sprite.Common.cs:line 266
   at DynamicSet(Object , Object )
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetPropertyInfo.Invoke(Object source, Object value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 98
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 492
   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378
   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52
   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 627
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\jusjohns\Documents\projects\MasteroidRedeux\MasteroidRedeux\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 347
   at GlueControl.Editing.VariableAssignmentLogic.SetVariable(GlueVariableSetData data, PositionedObject forcedItem) in C:\Users\jusjohns\Documents\projects\MasteroidRedeux\MasteroidRedeux\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 99
```

**Comment by vchelaru** [comment]
Fixed

5a058dc4f6057c64f52f439dffaeea5307698ca6
