### ISSUE TITLE
CtRL+click on add new animation/frame causes exception

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#630]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FlatRedBall.AnimationEditorForms.Preview.PreviewManager.UpdateShapes() in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\Preview\PreviewManager.cs:line 314
   at FlatRedBall.AnimationEditorForms.Preview.PreviewManager.ReactToAnimationFrameSelected() in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\Preview\PreviewManager.cs:line 416
   at FlatRedBall.AnimationEditorForms.TreeViewManager.AfterTreeItemSelect() in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\Managers\TreeViewManager.cs:line 329
   at FlatRedBall.AnimationEditorForms.MainControl.AnimationTreeView_AfterSelect(Object sender, TreeViewEventArgs e) in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\MainControl.cs:line 343
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at CommonFormsAndControls.MultiSelectTreeView.OnAfterSelect(TreeViewEventArgs e) in C:\Users\vchel\Documents\GitHub\Gum\CommonFormsAndControls\MultiSelectTreeView.cs:line 338
   at CommonFormsAndControls.MultiSelectTreeView.ReactToClickedNode(TreeNode node) in C:\Users\vchel\Documents\GitHub\Gum\CommonFormsAndControls\MultiSelectTreeView.cs:line 897
   at CommonFormsAndControls.MultiSelectTreeView.set_SelectedNode(TreeNode value) in C:\Users\vchel\Documents\GitHub\Gum\CommonFormsAndControls\MultiSelectTreeView.cs:line 100
   at FlatRedBall.AnimationEditorForms.SelectedState.set_SelectedNode(TreeNode value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\SelectedState.cs:line 82
   at FlatRedBall.AnimationEditorForms.SelectedState.set_SelectedFrame(AnimationFrameSave value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\SelectedState.cs:line 157
   at FlatRedBall.AnimationEditorForms.WireframeManager.CreateNewFrameFromTextureCoordinates(Int32 minX, Int32 minY, Int32 maxX, Int32 maxY) in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\Wireframe\WireframeManager.cs:line 288
   at FlatRedBall.AnimationEditorForms.WireframeManager.TryHandleMagicWandClicking() in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\Wireframe\WireframeManager.cs:line 236
   at FlatRedBall.AnimationEditorForms.WireframeManager.HandleClick(Object sender, EventArgs e) in C:\Users\vchel\Documents\GitHub\FlatRedBall\FRBDK\FlatRedBall.AnimationEditorForms\Wireframe\WireframeManager.cs:line 150
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by vchelaru** [comment]
Old issue
