### ISSUE TITLE
Clearing polygon points and resetting to square should not crash the editor

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#643]
Repro steps:

- Have a custom polygon (mine had 5 points)
- Be previewing the object (editor running)
- Click button to reset polygon to be a square
- Confirm choice
- Editor crashes, polygon list becomes temporarily empty

Expected result: polygon becomes a square and editor does not crash.

3:17:14 PM - System.IndexOutOfRangeException: Cannot set the Points property to an IList of 0 Points
   at FlatRedBall.Math.Geometry.Polygon.set_Points(IList`1 value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Math\Geometry\Polygon.cs:line 161
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\jusjohns\Documents\projects\MasteroidRedeux\MasteroidRedeux\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 311
   at GlueControl.Editing.VariableAssignmentLogic.SetVariable(GlueVariableSetData data, PositionedObject forcedItem) in C:\Users\jusjohns\Documents\projects\MasteroidRedeux\MasteroidRedeux\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 99
3:17:19 PM - System.IndexOutOfRangeException: Cannot set the Points property to an IList of 0 Points
   at FlatRedBall.Math.Geometry.Polygon.set_Points(IList`1 value) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Math\Geometry\Polygon.cs:line 161
   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\jusjohns\Documents\projects\MasteroidRedeux\MasteroidRedeux\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 311
   at GlueControl.Editing.VariableAssignmentLogic.SetVariable(GlueVariableSetData data, PositionedObject forcedItem) in C:\Users\jusjohns\Documents\projects\MasteroidRedeux\MasteroidRedeux\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 99

**Comment by vchelaru** [comment]
Fixed

754b39b59010c03f928f00659ecac8131d6049df
