### ISSUE TITLE
Editor should not "randomly" crash due to disposed textures

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#768]
I get this error seemingly at random when trying to run the game in the editor. The game works fine when I build it in VS so this is specifically an editor problem. It seems to happen when I'm using emitters heavily, especially `ScalableAreaEmitter` objects that have `PlayImmediately` set to `true` as a property.

This is Glue's call stack. I can't debug this because it happens immediately after compile and I can't attach VS fast enough to dig deeper:

11:17:12 AM - Launching game .exe timed out after 14 seconds.
The game has crashed:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The Sprite with the name "SpriteInstance" references a disposed texture of the name C:/Users/jusjohns/Documents/projects/BattleCryptBombers/BattleCryptBombers/bin/x86/debug/content/globalcontent/spritesheet.png.  If you're using Screens you may have forgotten to remove a Sprite that was added in the Screen.'.
   at FlatRedBall.Graphics.RenderBreak..ctor(Int32 itemNumber, Sprite sprite) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Graphics\RenderBreak.cs:line 109
   at FlatRedBall.Graphics.Renderer.FillVertexList(IList`1 sa, List`1 vertexLists, List`1 renderBreaks, Int32 firstSprite, Int32 numberToDraw) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Graphics\Renderer.cs:line 2680
   at FlatRedBall.Graphics.Renderer.PrepareSprites(List`1 spriteVertices, List`1 renderBreaks, IList`1 spritesToDraw, Int32 startIndex, Int32 numberOfVisible) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Graphics\Renderer.cs:line 2136
   at FlatRedBall.Graphics.Renderer.DrawMixed(SpriteList spriteListUnfiltered, SortType sortType, PositionedObjectList`1 textListUnfiltered, List`1 batches, Boolean relativeToCamera, Camera camera, Section section) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Graphics\Renderer.Common.cs:line 465
   at FlatRedBall.Graphics.Renderer.DrawOrderedByDistanceFromCamera(Camera camera, Section section) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Graphics\Renderer.Common.cs:line 1247
   at FlatRedBall.Graphics.Renderer.DrawUnlayeredObjects(Camera camera, RenderMode renderMode, Section section) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Graphics\Renderer.Common.cs:line 1092
   at FlatRedBall.Graphics.Renderer.DrawCamera(Camera camera, RenderMode renderMode, Section section) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Graphics\Renderer.Common.cs:line 1175
   at FlatRedBall.Graphics.Renderer.Draw(Section section) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Graphics\Renderer.cs:line 1139
   at FlatRedBall.FlatRedBallServices.RenderAll(Section section) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1499
   at FlatRedBall.FlatRedBallServices.Draw(Section section) in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1442
   at FlatRedBall.FlatRedBallServices.Draw() in C:\Users\jusjohns\Documents\projects\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\FlatRedBallServices.cs:line 1412
   at BattleCryptBombers.Game1.Draw(GameTime gameTime) in C:\Users\jusjohns\Documents\projects\BattleCryptBombers\BattleCryptBombers\Game1.cs:line 111
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at BattleCryptBombers.Program.Main() in C:\Users\jusjohns\Documents\projects\BattleCryptBombers\BattleCryptBombers\Program.cs:line 20

**Comment by vchelaru** [comment]
I believe I have improved and possibly fixed the bug, but I'm not sure because I can't reproduce it myself.

However, if it does reproduce, the additional diagnostics that @profexorgeek added will also be helpful.

I'm going to keep this open for  a little while to see if the crash has been fixed.

**Comment by vchelaru** [comment]
I believe this is fixed.
