### ISSUE TITLE
Gum.exe crash on object base type change

### ISSUE THREAD

**Issue by gascarcella** [vchelaru/FlatRedBall#87]
Steps to reproduce

1. Create a new project on `GlueFormsCore.exe` with default options
2. **Quick Actions** -> Add Gum Project -> Including Forms Control
3. **Quick Actions** -> Add Screen -> default options
5. Open the **GumProject.gumx** file on `Gum.exe` 
6. **Project** -> Screens -> Right click on **GameScreenGum** _the screen that you created on step 3_ -> Add object to ... -> Put any name
7. **Variables** -> Change "Base Type" to "Sprite"
8. **Variables** -> Change "Base Type" from "Sprite" to "Container" and Gum Instantly Crash
9. If it doest not crash, change from "Container"/"Sprite" to "Component"

Re-opening the project on Gum leads to an error when clicking on **GameScreenGum** _the screen that you created on step 3_ that will crash and close the app.
Tried different times and found the same error

**StackTrace** -- im cutting out the loaded assemblies to make it small --

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gum.Wireframe.WireframeObjectManager.CreateRectangleFor(InstanceSave instance, List`1 elementStack, GraphicalUiElement graphicalUiElement) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Wireframe\WireframeObjectManager.RepresentationCreation.cs:line 447
   at Gum.Wireframe.WireframeObjectManager.CreateRepresentationForInstance(InstanceSave instance, InstanceSave parentInstance, List`1 elementStack, GraphicalUiElement container) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Wireframe\WireframeObjectManager.RepresentationCreation.cs:line 260
   at Gum.Wireframe.WireframeObjectManager.CreateIpsoForElement(ElementSave elementSave) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Wireframe\WireframeObjectManager.RepresentationCreation.cs:line 140
   at Gum.Wireframe.WireframeObjectManager.RefreshAll(Boolean forceLayout, Boolean forceReloadTextures, ElementSave elementSave) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Wireframe\WireframeObjectManager.cs:line 252
   at Gum.Wireframe.WireframeObjectManager.RefreshAll(Boolean forceLayout, Boolean forceReloadTextures) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Wireframe\WireframeObjectManager.cs:line 218
   at Gum.ToolStates.SelectedState.UpdateToSelectedStateSave() in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\ToolStates\SelectedState.cs:line 591
   at Gum.Managers.StateTreeViewManager.OnSelect() in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Plugins\StatePlugin\StateTreeViewManager.cs:line 183
   at Gum.Controls.StateView.StateTreeView_AfterSelect(Object sender, TreeViewEventArgs e) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Controls\StateView.cs:line 67
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at CommonFormsAndControls.MultiSelectTreeView.OnAfterSelect(TreeViewEventArgs e) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\CommonFormsAndControls\MultiSelectTreeView.cs:line 333
   at CommonFormsAndControls.MultiSelectTreeView.ReactToClickedNode(TreeNode node) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\CommonFormsAndControls\MultiSelectTreeView.cs:line 892
   at CommonFormsAndControls.MultiSelectTreeView.set_SelectedNode(TreeNode value) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\CommonFormsAndControls\MultiSelectTreeView.cs:line 100
   at Gum.Managers.StateTreeViewManager.Select(TreeNode treeNode) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Plugins\StatePlugin\StateTreeViewManager.cs:line 214
   at Gum.Managers.StateTreeViewManager.Select(StateSave stateSave) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Plugins\StatePlugin\StateTreeViewManager.cs:line 194
   at Gum.ToolStates.SelectedState.set_SelectedStateSave(StateSave value) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\ToolStates\SelectedState.cs:line 281
   at Gum.ToolStates.SelectedState.UpdateToSelectedElement() in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\ToolStates\SelectedState.cs:line 539
   at Gum.Managers.ElementTreeViewManager.OnSelect(TreeNode selectedTreeNode) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Managers\ElementTreeViewManager.cs:line 1307
   at Gum.Managers.ElementTreeViewManager.ObjectTreeView_AfterClickSelect(Object sender, TreeViewEventArgs e) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\Gum\Managers\ElementTreeViewManager.cs:line 1353
   at CommonFormsAndControls.MultiSelectTreeView.OnMouseUp(MouseEventArgs e) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\CommonFormsAndControls\MultiSelectTreeView.cs:line 246
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at CommonFormsAndControls.MultiSelectTreeView.WndProc(Message& m) in C:\BuildAgent\work\a22593881c1cbdfe\Gum\CommonFormsAndControls\MultiSelectTreeView.cs:line 663
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

OS: Windows 10 20H2 19042.928

**Comment by vchelaru** [comment]
The bug was ultimately caused by Gum letting you pick Component as the base type, which it shouldn't let you do. I've removed that option, and also made Gum tolerate anything that may be set to that.
