### ISSUE TITLE
Selecting a tile collision object should not reset the game

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#940]
I believe this is because a variable is being sent over to the game and the game doesn't know how to deal with it, so it's restarting.

```
System.MemberAccessException: LateBinder could not find a field or property by the name of PartitioningAutomaticManual in the class FlatRedBall.TileCollisions.TileShapeCollection.  Check the name of the property to verify if it is correct.

   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetProperty[K](Object target, String propertyName, K value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 510

   at FlatRedBall.Instructions.Reflection.LateBinder`1.SetValue(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 378

   at FlatRedBall.Instructions.Reflection.LateBinder.SetValueStatic(Object target, String name, Object value) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Instructions\Reflection\LateBinder.cs:line 52

   at FlatRedBall.Screens.Screen.ApplyVariable(String variableName, Object value, Object container) in C:\Users\vchel\Documents\GitHub\FlatRedBall\Engines\FlatRedBallXNA\FlatRedBall\Screens\Screen.cs:line 632

   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInElement(Object variableValue, GlueVariableSetDataResponse response, Screen screen, String instanceName, String variableName, INameable targetInstance) in C:\Users\vchel\Documents\GitHub\BattleCryptBombers\BattleCryptBombers\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 401

   at GlueControl.Editing.VariableAssignmentLogic.SetValueOnObjectInScreen(GlueVariableSetData data, Object variableValue, GlueVariableSetDataResponse response, Screen screen) in C:\Users\vchel\Documents\GitHub\BattleCryptBombers\BattleCryptBombers\GlueControl\Editing\VariableAssignmentLogic.Generated.cs:line 198
Restarting because: Unhandled variable changed. Waiting for tasks to finish...
```

![28_07 56 44](https://user-images.githubusercontent.com/729631/215273322-a20db003-b307-42c3-ac3a-55df77fd6445.gif)

**Comment by vchelaru** [comment]
Fixed
